version: "3.9"  
services:
  backend:
    build: .
    environment: 
      - CONTAINER=1
    volumes: 
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports: 
      - 7070:7070
    networks: 
      - wafnet
  frontend:
    build: web/
    ports: 
      - 7000:80
networks: 
    wafnet:
        name: wafnet